name: Tests for Python Scripts

on:
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
    - uses: actions/checkout@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements-dev.txt

    - run: make format
    # - run: make lint

  # unit-test:
  #   runs-on: ubuntu-18.04
  #   defaults:
  #     run:
  #       shell: bash -l {0}

  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       python-version: 3.8

  #   - run: make utest
